backend:
  name: github
  repo: kevinjohannesson/my-gatsby-site
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - {
          name: category,
          label: Categorie,
          widget: "select",
          options: ["left", "center", "right"],
        }
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
